import { NORTHERN_CAMP } from "./campProtection";

export const WORLD_EVENTS = [
  {
    id: "wolf-invasion",
    name: "Wolf Invasion",
    announcement: "World Event: Wolves are attacking the Northern Camp!",
    center: NORTHERN_CAMP.center,
    participationRadius: 65,
    spawnRadius: 28,
    initialDelay: 120000,
    duration: 600000,
    cooldown: 600000,
    waveDelay: 10000,
    scaling: { healthPerExtraPlayer: 0.75, damagePerExtraPlayer: 0.15 },
    waves: [
      { type: "wolf", level: 5, count: 3 },
      { type: "wolf", level: 7, count: 3 },
      { type: "wolf", level: 9, count: 3 },
    ],
    boss: { type: "alphaWolf", level: 11, count: 1 },
    rewards: { xp: 500, money: 10000, lootType: "wolf" },
  },
  {
    id: "forest-giant-awakening",
    name: "Forest Giant Awakening",
    announcement: "World Event: The Forest Giant has awakened!",
    center: { x: 200, z: -200 },
    participationRadius: 65,
    spawnRadius: 0,
    initialDelay: 120000,
    duration: 600000,
    cooldown: 600000,
    waveDelay: 0,
    scaling: { healthPerExtraPlayer: 0.75, damagePerExtraPlayer: 0.15 },
    waves: [],
    boss: { type: "awakenedForestGiant", level: 8, count: 1 },
    rewards: { xp: 1000, money: 20000, lootType: "awakenedForestGiant" },
  },
];
